# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 00:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0002_auto_20171226_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='concerned_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='关注者'),
        ),
    ]
