# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-13 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0005_auto_20180108_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='view_nums',
        ),
    ]
