# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 02:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0006_remove_article_view_nums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='concerned_users',
            field=models.ManyToManyField(related_name='concerned_questions', to=settings.AUTH_USER_MODEL, verbose_name='关注者'),
        ),
    ]
