# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd_input_wrong_times',
            field=models.IntegerField(default=0, verbose_name='修改密码错误次数'),
        ),
    ]
