# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_pwd_input_wrong_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]
